// flow-typed signature: 9e9b4e97e62673d472b3aac43e9a81a7
// flow-typed version: <<STUB>>/eslint-config-brainly-react_v2.1.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-brainly-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-brainly-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-brainly-react/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-brainly-react/rules/redux' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-brainly-react/index' {
  declare module.exports: $Exports<'eslint-config-brainly-react'>;
}
declare module 'eslint-config-brainly-react/index.js' {
  declare module.exports: $Exports<'eslint-config-brainly-react'>;
}
declare module 'eslint-config-brainly-react/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-brainly-react/rules/react'>;
}
declare module 'eslint-config-brainly-react/rules/redux.js' {
  declare module.exports: $Exports<'eslint-config-brainly-react/rules/redux'>;
}
