// flow-typed signature: 413f740e5d93fd66bcbfd2237e7d7ff8
// flow-typed version: <<STUB>>/frontend-tools-configs_vgit+https://github.com/brainly/frontend-tools-configs.git#v16.2.7/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'frontend-tools-configs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'frontend-tools-configs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'frontend-tools-configs/eslint/babel' {
  declare module.exports: any;
}

declare module 'frontend-tools-configs/eslint/flow' {
  declare module.exports: any;
}

declare module 'frontend-tools-configs/eslint/legacy' {
  declare module.exports: any;
}

declare module 'frontend-tools-configs/eslint/main' {
  declare module.exports: any;
}

declare module 'frontend-tools-configs/eslint/react' {
  declare module.exports: any;
}

declare module 'frontend-tools-configs/eslint/redux' {
  declare module.exports: any;
}

// Filename aliases
declare module 'frontend-tools-configs/eslint/babel.js' {
  declare module.exports: $Exports<'frontend-tools-configs/eslint/babel'>;
}
declare module 'frontend-tools-configs/eslint/flow.js' {
  declare module.exports: $Exports<'frontend-tools-configs/eslint/flow'>;
}
declare module 'frontend-tools-configs/eslint/legacy.js' {
  declare module.exports: $Exports<'frontend-tools-configs/eslint/legacy'>;
}
declare module 'frontend-tools-configs/eslint/main.js' {
  declare module.exports: $Exports<'frontend-tools-configs/eslint/main'>;
}
declare module 'frontend-tools-configs/eslint/react.js' {
  declare module.exports: $Exports<'frontend-tools-configs/eslint/react'>;
}
declare module 'frontend-tools-configs/eslint/redux.js' {
  declare module.exports: $Exports<'frontend-tools-configs/eslint/redux'>;
}
