// flow-typed signature: 9e235364b3631e9b6c786189159d9f21
// flow-typed version: <<STUB>>/superstatic_v^6.0.4/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superstatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superstatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superstatic/bin/update-notifier' {
  declare module.exports: any;
}

declare module 'superstatic/examples/middleware/index' {
  declare module.exports: any;
}

declare module 'superstatic/examples/server/index' {
  declare module.exports: any;
}

declare module 'superstatic/lib/activator' {
  declare module.exports: any;
}

declare module 'superstatic/lib/cli/flags' {
  declare module.exports: any;
}

declare module 'superstatic/lib/cli/index' {
  declare module.exports: any;
}

declare module 'superstatic/lib/cli/server' {
  declare module.exports: any;
}

declare module 'superstatic/lib/index' {
  declare module.exports: any;
}

declare module 'superstatic/lib/loaders/config-file' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/env' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/files' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/headers' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/index' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/missing' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/not-found' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/protect' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/redirects' {
  declare module.exports: any;
}

declare module 'superstatic/lib/middleware/rewrites' {
  declare module.exports: any;
}

declare module 'superstatic/lib/providers/fs' {
  declare module.exports: any;
}

declare module 'superstatic/lib/providers/memory' {
  declare module.exports: any;
}

declare module 'superstatic/lib/responder' {
  declare module.exports: any;
}

declare module 'superstatic/lib/server' {
  declare module.exports: any;
}

declare module 'superstatic/lib/superstatic' {
  declare module.exports: any;
}

declare module 'superstatic/lib/utils/global-install' {
  declare module.exports: any;
}

declare module 'superstatic/lib/utils/global-resolve' {
  declare module.exports: any;
}

declare module 'superstatic/lib/utils/npm-paths' {
  declare module.exports: any;
}

declare module 'superstatic/lib/utils/pathutils' {
  declare module.exports: any;
}

declare module 'superstatic/lib/utils/promiseback' {
  declare module.exports: any;
}

declare module 'superstatic/test/helpers' {
  declare module.exports: any;
}

declare module 'superstatic/test/integration/clean-urls.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/integration/error-pages.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/integration/serving-files.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/cli/index.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/cli/services.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/loaders/config-file.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/middleware/env.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/middleware/files.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/middleware/headers.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/middleware/missing.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/middleware/not-found.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/middleware/redirects.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/middleware/rewrites.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/providers/fs.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/providers/memory.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/responder.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/server.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/superstatic.spec' {
  declare module.exports: any;
}

declare module 'superstatic/test/unit/utils/promiseback.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superstatic/bin/update-notifier.js' {
  declare module.exports: $Exports<'superstatic/bin/update-notifier'>;
}
declare module 'superstatic/examples/middleware/index.js' {
  declare module.exports: $Exports<'superstatic/examples/middleware/index'>;
}
declare module 'superstatic/examples/server/index.js' {
  declare module.exports: $Exports<'superstatic/examples/server/index'>;
}
declare module 'superstatic/lib/activator.js' {
  declare module.exports: $Exports<'superstatic/lib/activator'>;
}
declare module 'superstatic/lib/cli/flags.js' {
  declare module.exports: $Exports<'superstatic/lib/cli/flags'>;
}
declare module 'superstatic/lib/cli/index.js' {
  declare module.exports: $Exports<'superstatic/lib/cli/index'>;
}
declare module 'superstatic/lib/cli/server.js' {
  declare module.exports: $Exports<'superstatic/lib/cli/server'>;
}
declare module 'superstatic/lib/index.js' {
  declare module.exports: $Exports<'superstatic/lib/index'>;
}
declare module 'superstatic/lib/loaders/config-file.js' {
  declare module.exports: $Exports<'superstatic/lib/loaders/config-file'>;
}
declare module 'superstatic/lib/middleware/env.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/env'>;
}
declare module 'superstatic/lib/middleware/files.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/files'>;
}
declare module 'superstatic/lib/middleware/headers.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/headers'>;
}
declare module 'superstatic/lib/middleware/index.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/index'>;
}
declare module 'superstatic/lib/middleware/missing.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/missing'>;
}
declare module 'superstatic/lib/middleware/not-found.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/not-found'>;
}
declare module 'superstatic/lib/middleware/protect.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/protect'>;
}
declare module 'superstatic/lib/middleware/redirects.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/redirects'>;
}
declare module 'superstatic/lib/middleware/rewrites.js' {
  declare module.exports: $Exports<'superstatic/lib/middleware/rewrites'>;
}
declare module 'superstatic/lib/providers/fs.js' {
  declare module.exports: $Exports<'superstatic/lib/providers/fs'>;
}
declare module 'superstatic/lib/providers/memory.js' {
  declare module.exports: $Exports<'superstatic/lib/providers/memory'>;
}
declare module 'superstatic/lib/responder.js' {
  declare module.exports: $Exports<'superstatic/lib/responder'>;
}
declare module 'superstatic/lib/server.js' {
  declare module.exports: $Exports<'superstatic/lib/server'>;
}
declare module 'superstatic/lib/superstatic.js' {
  declare module.exports: $Exports<'superstatic/lib/superstatic'>;
}
declare module 'superstatic/lib/utils/global-install.js' {
  declare module.exports: $Exports<'superstatic/lib/utils/global-install'>;
}
declare module 'superstatic/lib/utils/global-resolve.js' {
  declare module.exports: $Exports<'superstatic/lib/utils/global-resolve'>;
}
declare module 'superstatic/lib/utils/npm-paths.js' {
  declare module.exports: $Exports<'superstatic/lib/utils/npm-paths'>;
}
declare module 'superstatic/lib/utils/pathutils.js' {
  declare module.exports: $Exports<'superstatic/lib/utils/pathutils'>;
}
declare module 'superstatic/lib/utils/promiseback.js' {
  declare module.exports: $Exports<'superstatic/lib/utils/promiseback'>;
}
declare module 'superstatic/test/helpers.js' {
  declare module.exports: $Exports<'superstatic/test/helpers'>;
}
declare module 'superstatic/test/integration/clean-urls.spec.js' {
  declare module.exports: $Exports<'superstatic/test/integration/clean-urls.spec'>;
}
declare module 'superstatic/test/integration/error-pages.spec.js' {
  declare module.exports: $Exports<'superstatic/test/integration/error-pages.spec'>;
}
declare module 'superstatic/test/integration/serving-files.spec.js' {
  declare module.exports: $Exports<'superstatic/test/integration/serving-files.spec'>;
}
declare module 'superstatic/test/unit/cli/index.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/cli/index.spec'>;
}
declare module 'superstatic/test/unit/cli/services.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/cli/services.spec'>;
}
declare module 'superstatic/test/unit/loaders/config-file.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/loaders/config-file.spec'>;
}
declare module 'superstatic/test/unit/middleware/env.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/middleware/env.spec'>;
}
declare module 'superstatic/test/unit/middleware/files.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/middleware/files.spec'>;
}
declare module 'superstatic/test/unit/middleware/headers.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/middleware/headers.spec'>;
}
declare module 'superstatic/test/unit/middleware/missing.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/middleware/missing.spec'>;
}
declare module 'superstatic/test/unit/middleware/not-found.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/middleware/not-found.spec'>;
}
declare module 'superstatic/test/unit/middleware/redirects.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/middleware/redirects.spec'>;
}
declare module 'superstatic/test/unit/middleware/rewrites.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/middleware/rewrites.spec'>;
}
declare module 'superstatic/test/unit/providers/fs.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/providers/fs.spec'>;
}
declare module 'superstatic/test/unit/providers/memory.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/providers/memory.spec'>;
}
declare module 'superstatic/test/unit/responder.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/responder.spec'>;
}
declare module 'superstatic/test/unit/server.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/server.spec'>;
}
declare module 'superstatic/test/unit/superstatic.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/superstatic.spec'>;
}
declare module 'superstatic/test/unit/utils/promiseback.spec.js' {
  declare module.exports: $Exports<'superstatic/test/unit/utils/promiseback.spec'>;
}
